### ISSUE TITLE
syntax error "unexpected RPAREN_TOK"

### ISSUE THREAD

**Issue by RobinDavid** [stp/stp#232]
Hi all,

I am trying to solve formulas with STP, but I am encountering issues manipulating arrays. The code snippet is the following:

```
(set-logic QF_ABV) 
(set-info :smt-lib-version 2.0)

(declare-fun arr1 () (Array (_ BitVec 8) (_ BitVec 8)))
(declare-fun x () (_ BitVec 8))
(define-fun arr2 () (Array (_ BitVec 8) (_ BitVec 8)) (store arr1 #x03 #xaa))

(assert (= x (select arr2 #x03)))

(check-sat)
(get-model)
```

I raises: `(error "syntax error: line 6 syntax error, unexpected RPAREN_TOK, expecting end of file or LPAREN_TOK  token: )")`

I am probably doing it wrong with the `define-fun`, but it works perfectly fine with the other solvers I have tried. I guess you can help me figuring what is wrong ?

Regards,

**Comment by msoos** [comment]
Well, it complains about line 5. That line has a bit too many `)`, right?

```
(declare-fun x () (_ BitVec 8)))
```

That should fix the issue.

**Comment by RobinDavid** [comment]
Sorry, I did a typo will writing the snippet but the issue is still there even without the ")" :cry:

**Comment by TrevorHansen** [comment]
I've changed it so that we parse these now, and report "unsupported".

I don't know whether we can support array define-functions. At the moment we don't have extensionality, which we might need to support these? I don't know.

**Comment by RobinDavid** [comment]
Thank's for the changing, this is way more explicit now!

I didn't knew it was extensionality. I don't want to give you a work overload, but that would be cool :wink: (to include stp in some of my benchmarks)
As far as I know Z3, boolector, CV4 and Yices support array as return type of define-function but for instance boolector does not support array as parameter of define-funs.

**Comment by msoos** [comment]
Yeah, that would be a different issue, arrays. I'll close this. Unfortunately, there is no plan for that at the moment. Maybe later, or maybe if you could work a bit on it, we could potentially take it from there. It'd be great to have someone hack a bit :) Until then, let me close this issue, as that's another issue (a feature request). Cheers and thanks for getting back to us!
